services:
  redis:
    image: redis:latest
    container_name: perlis-redis
    ports:
      - "6379:6379"
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: perlis-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - RECAPTCHA_DISABLED=true
